### ISSUE TITLE
Feature or new tool idea.

### ISSUE THREAD

**Issue by vinnn-90** [vibovenkat123/review-gpt#11]
Hi, 

I realize this is not the perfect place to ask, but I found no other way to contact you. 
And please forgive me for not being able to find the perfect words to describe, I am still a beginner trying to learn python.

I just want to express my interest in a feature or new program working with gpt ai.
I am using ChatGPT on a daily basis to ask about my code while learning.
Currently I am working on a repo with ~ 6 files,  5 .py and 1 .json. I try to use proper organisation and split my modules into different files, then import them etc...

Now when I have a question I have to send ChatGPT a message including the names and code content of all my files,  followed by my question. I realize that this wouldnt work with larger codebases, but with 6 files, this still works well at the moment. ChatGPT understands the relation of my files and modules and replies proper code examples and changes for each file.

It would be amazing for a beginner like me to be able to skip the copy/paste part. A simple feature or tool where I could chose files to  include in my ChatGPT request before asking my question.

I looked through all the gpt extensions for VSCode but none of them have this feature. I believe this is because no-one thinks of "us" beginners, and for larger codebases ChatGPT would probably not be able to handle it.

However I think there are plenty of people like me for whom this would be a life saver while learning a programming language.

Anyway, good luck with your current projects!
Kind regards!

**Comment by vaibhav-venkat** [comment]
When you are asking Chat GPT, are you asking for help on what the code you are writing does? (e.g "What does function x do"). Or are you asking Chat GPT to do something with the code? (e.g Rename variable x to y). Also if this is not related to Review-GPT and you just want to suggest something to me personally, you can email me at <vibovenkat@gmail.com>

**Comment by vinnn-90** [comment]
Thanks for replying!
Will send some examples in a mail later today!
